# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dOB',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
