# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dOB',
        ),
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
