# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_auto_20171119_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
