# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_auto_20171119_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='review_count',
        ),
    ]
