# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0007_auto_20171120_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('favoritedUser', models.ManyToManyField(related_name='favorite_quotes', to='login_registration.User')),
                ('userPosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='login_registration.User')),
            ],
        ),
    ]
